//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _25082022_ödev
{
    using System;
    using System.Collections.Generic;
    
    public partial class Musteri
    {
        public int MusteriID { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string HesapNumarası { get; set; }
        public string TcNo { get; set; }
        public int BankaID { get; set; }
    
        public virtual Banka Banka { get; set; }
    }
}
